name: Paper Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Download and Run Paper
        run: |
          mkdir server
          cd server
          
          # Paper 1.21 (Stable)
          wget https://api.papermc.io/v2/projects/paper/versions/1.21/builds/latest/downloads/paper-1.21-latest.jar
          
          echo "eula=true" > eula.txt
          
          java -Xmx8G -Xms4G -jar paper-1.21-latest.jar nogui
